### ISSUE TITLE
Implement sponsors view

### ISSUE THREAD

**Issue by ghost** [72Fest/ng2-72-film-fest#9]
- [x] find new 72fest.com sponsors page
- [x] incorporate in-app browser

**Comment by LonnyGomes** [comment]
@shrtminded is there a new URL for the sponsors page? The previous one no longer works

**Comment by shrtminded** [comment]
@LonnyGomes the URL is http://72fest.com/sponsors/ ... It was take down by mistake.  It is backup and being cleaned up.
